#!/bin/bash
# ExVenture Morning Brief → NotebookLM Video → Slack Pipeline
# Runs daily at 11 AM Barcelona time

set -euo pipefail

NOTEBOOKLM="/Users/franzccm/Library/Python/3.14/bin/notebooklm"
SLACK_WEBHOOK="SLACK_WEBHOOK_PLACEHOLDER"
BRIEF_DIR="/tmp/morningbrief"
DATE=$(date +"%A, %B %d, %Y")
DATE_SHORT=$(date +"%Y-%m-%d")

mkdir -p "$BRIEF_DIR"

echo "=== ExVenture Morning Brief Pipeline ==="
echo "Date: $DATE"

# ─── STEP 1: Check if brief text exists (generated by Claude trigger or passed as arg) ───
BRIEF_FILE="$BRIEF_DIR/brief_${DATE_SHORT}.md"

if [ -n "${1:-}" ] && [ -f "$1" ]; then
    BRIEF_FILE="$1"
    echo "Using provided brief: $BRIEF_FILE"
elif [ ! -f "$BRIEF_FILE" ]; then
    echo "ERROR: No brief file found at $BRIEF_FILE"
    echo "Generate the brief first or pass the file path as argument."
    exit 1
fi

echo "Brief file: $BRIEF_FILE"

# ─── STEP 2: Create NotebookLM notebook ───
echo ""
echo "=== Creating NotebookLM notebook ==="
NOTEBOOK_JSON=$($NOTEBOOKLM create "AI Morning Brief — $DATE" --json 2>&1) || {
    echo "Failed to create notebook. Output: $NOTEBOOK_JSON"
    exit 1
}
NOTEBOOK_ID=$(echo "$NOTEBOOK_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])" 2>/dev/null || echo "$NOTEBOOK_JSON" | grep -oE '[a-f0-9-]{36}' | head -1)
echo "Notebook created: $NOTEBOOK_ID"

# Set as current notebook
$NOTEBOOKLM use "$NOTEBOOK_ID"

# ─── STEP 3: Add brief as source ───
echo ""
echo "=== Adding brief as source ==="
$NOTEBOOKLM source add "$BRIEF_FILE" --title "Morning Brief — $DATE" --type text

# Wait for source to be processed
echo "Waiting for source processing..."
sleep 5
$NOTEBOOKLM source wait 2>/dev/null || sleep 10

# ─── STEP 4: Generate video overview ───
echo ""
echo "=== Generating video overview ==="
$NOTEBOOKLM generate video "Create a professional, energetic video briefing summarizing today's AI industry news. Present it like a morning news show - highlight the #1 priority action, key product launches, insider intel, and market moves. Keep the tone sharp, conversational, and actionable." \
    --format brief \
    --style classic \
    --wait \
    --retry 3

# ─── STEP 5: Download the video ───
echo ""
echo "=== Downloading video ==="
VIDEO_FILE="$BRIEF_DIR/morningbrief_${DATE_SHORT}.mp4"
$NOTEBOOKLM download video "$VIDEO_FILE" --force --latest

if [ ! -f "$VIDEO_FILE" ]; then
    echo "ERROR: Video file not found after download"
    exit 1
fi

VIDEO_SIZE=$(du -h "$VIDEO_FILE" | cut -f1)
echo "Video downloaded: $VIDEO_FILE ($VIDEO_SIZE)"

# ─── STEP 6: Make notebook public and get share link ───
echo ""
echo "=== Getting share link ==="
$NOTEBOOKLM share public --enable 2>/dev/null || true
SHARE_STATUS=$($NOTEBOOKLM share status --json 2>&1) || true
SHARE_LINK=$(echo "$SHARE_STATUS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('public_url',''))" 2>/dev/null || echo "")

# ─── STEP 7: Upload video to Slack via API ───
echo ""
echo "=== Posting to Slack ==="

# Post the video link and summary to Slack
SLACK_MSG="*:tv: AI Morning Brief — Video Edition*\n*$DATE*\n\n:rotating_light: Your daily AI intelligence briefing is ready as a video!\n\n"

if [ -n "$SHARE_LINK" ]; then
    SLACK_MSG="${SLACK_MSG}:point_right: *Watch the full video briefing:* $SHARE_LINK\n\n"
fi

SLACK_MSG="${SLACK_MSG}_Compiled by ExVenture AI Research Team | Next brief: tomorrow 11:00am_"

python3 -c "
import json, urllib.request
msg = '''$SLACK_MSG'''
data = json.dumps({'text': msg}).encode()
req = urllib.request.Request('$SLACK_WEBHOOK', data=data, headers={'Content-Type': 'application/json'})
resp = urllib.request.urlopen(req)
print(f'Slack response: {resp.read().decode()}')
"

echo ""
echo "=== Pipeline complete ==="
echo "Video: $VIDEO_FILE"
[ -n "$SHARE_LINK" ] && echo "Share link: $SHARE_LINK"
echo "Posted to Slack: #ai-updates"
